### ISSUE TITLE
Forking notice ?

### ISSUE THREAD

**Issue by Sharlaan** [MaximilianPichler/material-ui-selectfield#13]
Hi Maximilian

Nice initiative to try by yourself, but wouldnot it be more polite and more inline with opensource mind to make a fork from my project, instead of mounting a new repo and blatantly copy-paste ?

Same with responding in my project's issues with a link here ?

Best regards,

**Comment by TarikHuber** [comment]
Hi @Sharlan,

It's not only Maximilian. We made it together. The reason is that we used
this project in our production project and we can't wait on you for weeks
to publish a new version. We even do the work and send PRs that are fixing
problems and you accept them. But without publishing them it is uselles for
us! So we made that project as a backup plan if you don't respond. Open
source means also that one project is managed by more than one person so it
is maintainable if that one has no tim for it. If you add more contributors
that can publish PRs to npm we will delete our Project/Fork. It is 100%
compatible with yours and ao easy to reoplace. I also would rather add new
features to your established projext than a new one. But if you don't
respond or publish it is uselles bot just for us but also for other. It is
up to you if you add more contributors or not. But without at least 2 a
project should not be added to a production project.

Am 12.10.2017 4:35 nachm. schrieb "Raphaël Morineau" <
notifications@github.com>:

**Comment by FDiskas** [comment]
@Sharlaan 
I even planning to make a copy of this repo to make some changes and use it in production. But currently this guy's responding and fixing quickly enough. :anguished:

Peace :anger:

**Comment by MaximilianPichler** [comment]
Hey!
I didn't mean to angry you by copying your code! As @TarikHuber stated, it would be best if we had one package with all features/fixes. So we would love to work together with you on this project!
Sadly we have very tight deadlines, so we need some fixes very fast. That's the reason why we made our own package.
I will delete my repo if we merge them. If you do not want to merge them, I will surely link to your repo and state clearly, that it is a fork .
So again sorry and we would love to collaborate with you!
Greetings

**Comment by FDiskas** [comment]
But probably it would be fear to add some note to the readme.

**Comment by Sharlaan** [comment]
@MaximilianPichler & @TarikHuber 
I'm totally agreed with you, just i never seen/received any request from any of you to become contributor o.O ??
i have no problem with adding more contributors to one single project, as long we discuss together regarding debatable topics.

I have now more free time to contribute to the project, and started to fix issues / merge PRs... and answer XD. Sorry if i seemed slacking ;)

**Comment by TarikHuber** [comment]
@Sharlaan I asked you to have access to the npm publishing months ago

**Comment by FDiskas** [comment]
p.s. the publishing to NPM should be done with travis not by devs. So there will be no need to add contributors to npm

**Comment by TarikHuber** [comment]
@FDiskas we are on to it ;)
